CREATE TABLE content (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content_type INTEGER NOT NULL,
    content VARCHAR,
    create_time TIMESTAMP(0) WITHOUT TIME ZONE,
    update_time TIMESTAMP(0) WITHOUT TIME ZONE
);

CREATE TABLE content_type (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TRIGGER CON_TYP AFTER INSERT ON content_type FOR EACH ROW CALL "com.sander.worklogger.trigger.H2Trigger"